services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn agilemetrics.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app/
      - static_volume:/app/staticfiles
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${POSTGRES_URL}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  static_volume:
  postgres_data:
